config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :matches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
	has_attached_file :pic1,
		styles: { standard: ["300x300#", :jpg] }

	has_attached_file :pic2,
		styles: { standard: ["300x300#", :jpg] }


	validates_attachment :pic1,
		content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }


	validates_attachment :pic2,
		content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }


	def self.shuffled_deck(match_count)
		pics_array =[]
		ids = Match.pluck(:id).shuffle
			match_count = 8 if match_count === ''
			shuffled_ids = ids[0..match_count.to_i - 1]
			shuffled_ids.each do |id|
			pics_array << { id => Match.find(id).pic1}
			pics_array << { id => Match.find(id).pic2}
		end
		pics_array.shuffle
	end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@cards = Match.shuffled_deck(params[:match_count])
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	before_action :match, except: [:index, :new, :create]

  def index
  	@matches = Match.all
  end

  def show
  end

  def new
  	@match = Match.new
  end

  def create
  	@match = Match.new(match_params)

  	if @match.save
  		redirect_to matches_path
  	else
  		render(:new)
  	end
  end

  def edit
  end

  def update
  	if @match.update(match_params)
  		redirect_to matches_path
  	else
  		render(:edit)
  	end
  end

  def destroy
  	@match.destroy
  	redirect_to matches_path
  end

  private

  def match_params
  	params.require(:match).permit(:pair_name, :pic1, :pic2)
  end

  def match
  	@match = Match.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/home/index.html.erb
<h1>Memory Game</h1>
<div class='row'>
	<form>
	<button id='reshuffle' class='btn col s2'>Reshuffle</button>
	<input name='match_count' type='number' placeholder='How many matches do you want?' class='col s6'/>
	</form>
</div>

<div class='row'>
<% @cards.each do |card| %>
	<div class='col s3 card' id=<%= card %> >
	<%= image_tag(card[card.keys[0]].url(:standard), title: card.keys[0], class: 'image no-display') %>
	</div> 
<% end %>
</div>	

<button id='replay_same_deck' class='no-display btn'>Replay same deck</button>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoryGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Paaji|Montserrat" rel="stylesheet">

  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to 'Memory!', root_path %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li> <%= link_to 'Uploaded Photos', matches_path %> </li>
          <li> <%= link_to 'New Game', root_path %> </li>
        </ul>
      </div>
    </nav>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_for @match do |f| %>


	<%= f.label :pair_name, 'Name Your Match' %>
	<%= f.text_field :pair_name, placeholder: 'person, place or thing' %>

	<div class='row'>
		<div class=' col s12 m6'>
			<%= f.label :pic1, 'Upload Picture 1', class: 'btn-large' %>
			<span style='display:none'> <%= f.file_field :pic1 %> </span>
		</div>

		<div class='col s12 m6'>
			<%= f.label :pic2, 'Upload Picture 2', class: 'btn-large' %>
			<span style='display:none'> <%= f.file_field :pic2 %>
		</div>

		<div class='col s12' id='submit-button'>
			<%= f.submit class: 'btn-large col s12' %>
		</div>
	</div>

<% end %>

app/views/matches/edit.html.erb
<h1>Edit Match: <%= @match.pair_name %> </h1>

<%= render(partial: 'form') %>

app/views/matches/index.html.erb
<h1>All Matches</h1>

<%= link_to 'Add New Match', new_match_path, class: 'btn' %>

<ul>
<% @matches.each do |match| %>
	<li>
		<div class='row'>
			<div class='col s6 m4'>
				 <h4> <%= link_to match.pair_name, match_path(match) %> </h4>
			</div>
			<div class='col s6 m2'>
				<h4> <%= link_to 'Edit', edit_match_path(match)%> </h4>	
		</div>
	</li>
<% end %>
</ul>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render(partial: 'form') %>

app/views/matches/show.html.erb
<h1>Match: <%= @match.pair_name %> </h1>

<%= link_to 'Edit this Match', edit_match_path(@match), class: 'btn' %>

<div class='row'>
	<div class='col s12 m4 offset-m1'>
		<h4> Picture 1 </h4>
		<%= image_tag(@match.pic1.url(:standard)) %>
	</div>

	<div class='col s12 m4 offset-m1'>
		<h4> Picture 2 </h4>
		<%= image_tag(@match.pic2.url(:standard)) %>
	</div>
</div>